[package]
name = "pull_payments"
version = "1.0.0"
authors = []

[addresses]
pull='db7474c7c8059257d1bc20f76501b4ae6979c4f3009f718270ef5e58b7703b04'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
