[package]
name = "pull_payments"
version = "1.0.0"
authors = []

[addresses]
pull='0d29f56956b2added737d49b110277fcf965dfd8df75297f0eef249d4f7bd304'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
